Models/studyGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace u23564556_Practical_02.Models
{
	public class studyGroup
	{
        [Key] // Primary key
        [Display(Name = "Student Number")]
        public string StudentNumber { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Current Age")]
        public int Age { get; set; } = 0;

        [Display(Name = "Living Status")]
        public bool IsAlive { get; set; } = true;

        [Display(Name = "Email Adress")]
        public string EmailAddress { get; set; }

        [Display(Name = "Link")]
        public string myLink { get; set; }

        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace u23564556_Practical_02.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/studyGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace u23564556_Practical_02.Controllers
{
    public class studyGroupController : Controller
    {
        // GET: People
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Names()
        {
            List<Models.studyGroup> members = new List<Models.studyGroup>();
            {
                members.Add(new Models.studyGroup { StudentNumber = "u23564556", FirstName = "Scott", LastName = "Allen", Age = 20, IsAlive = true, EmailAddress = "scott.doe@tuks.co.za", myLink = "~/HTML/Scott.html"  });
                members.Add(new Models.studyGroup { StudentNumber = "u24852504", FirstName = "Kallie", LastName = "Kotze", Age = 19, IsAlive = true, EmailAddress = "kallie.doe@tuks.co.za", myLink = "~/HTML/Kallie.html"  });
                members.Add(new Models.studyGroup { StudentNumber = "u24637646", FirstName = "Xario", LastName = "Zeekoei", Age = 19, IsAlive = true, EmailAddress = "xari.zee@tuks.co.za", myLink = "~/HTML/Xario.html"  });
                members.Add(new Models.studyGroup { StudentNumber = "u24521793", FirstName = "Yaasir", LastName = "Yacoob", Age = 19, IsAlive = true, EmailAddress = "yaasir.yaa@tuks.co.za", myLink = "~/HTML/Yaasir.html"  });
                members.Add(new Models.studyGroup { StudentNumber = "u24647686", FirstName = "Nabeeha", LastName = "Mohammad", Age = 19, IsAlive = true, EmailAddress = "nabeeha.moh@tuks.co.za", myLink = "~/HTML/Nabeeha.html"  });
            };
            return View(members);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Table of Names", "Names", "studyGroup", new { area = ""}, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/StudyGroup/Names.cshtml
@{
    ViewBag.Title = "Names";
}

<h2>Names</h2>
@model IEnumerable<u23564556_Practical_02.Models.studyGroup>

<table class ="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.StudentNumber) </th>
            <th>@Html.DisplayNameFor(model => model.FirstName) </th>
            <th>@Html.DisplayNameFor(model => model.LastName) </th>
            <th>@Html.DisplayNameFor(model => model.EmailAddress) </th>
            <th>Link to Personal Page</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var member in Model)
            {
                <tr>
                    <td>@member.StudentNumber</td>
                    <td>@member.FirstName</td>
                    <td>@member.LastName</td>
                    <td>@member.EmailAddress</td>
                    <td><a href ="@Url.Content(member.myLink)" class="button">LINK</a></td>
                </tr>
            }
    </tbody>
</table>